### PR TITLE
Bulk song queuing

### PR DESCRIPTION
**Pull request by lucasdepetrisd**
Hey there! This is a pull request from my forked repo. I included the new feature that allows adding songs in bulk to the playlist, as well as a variable to track the number of songs added. Also solved the previous confusion with the changes.

About the feature and the code, I think it'll help to add a limit of the songs that can be added to the playlist before merging branches as to avoid memory failure. Additionally, it seems to me that the click listener of X can be moved from scanCwd to the inputHandler.

If you have any questions or feedback, feel free to communicate. Thank you for considering my contribution!

### CODE REVIEW

**Comment by HookedBehemoth** [comment]
Thanks for the PR!
I made some small changes to it. I don't think any of the added class fields were really necessary.
The pointless lambda capture of FsDir pointed me to a clear handle leak that I resolved too.

I'm not too happy with the info message in the list but doing it properly - adding a toast or similar - would be too much effort for this.

**Comment by lucasdepetrisd** [comment]
Thanks for the changes! I ran into the same issue with the message to the user's input, so I agree that it's better to leave it. In any case, as for the A button, I think it would be cool to implement the alert function to give a response when adding individual songs.

**Comment by HookedBehemoth** [comment]
Added a poor man's toast and modify-able button descriptions 
img

**Comment by HookedBehemoth** [comment]
Couldn't merge this yet, as there is still an issue. Songs are added in folder order and should be added as they are displayed (alphabetically sorted rn)

**Comment by lucasdepetrisd** [comment]
### ee29430d4c3669cc2d8d99bd01bec76d6af5ea09


### 366f7b69b9c74c4e696e48641a7adec6ac501c3f

**Comment by HookedBehemoth** [comment]
This will leak memory on bulk add as you create tsl::elm::ListItem and never free them.
In the old code, those elements were given to libtesla which eventually cleans them up.

You should probably not even use the ListItem's here at all. Just make a `vector<char[FS_MAX_PATH]` or vector<FsDirectoryEntry> and sort those.

**Comment by HookedBehemoth** [comment]
Also I don't see why the frame in PlaylistGui is now a field. We're not using it anywhere else.

**Comment by lucasdepetrisd** [comment]
> This will leak memory on bulk add as you create tsl::elm::ListItem and never free them. In the old code, those elements were given to libtesla which eventually cleans them up.
> 
> You should probably not even use the ListItem's here at all. Just make a `vector<char[FS_MAX_PATH]` or vector and sort those.

I tried with a `vector<char[FS_MAX_PATH]>` but I found it a bit of a hassle to work with, so I turned to strings which are simpler and provides automatic memory management.
Additionally, I think I'm confused, but shouldn't the `std::vector<tsl::elm::ListItem *> folders, files;` in scanCwd also cause memory leak?

> Also I don't see why the frame in PlaylistGui is now a field. We're not using it anywhere else.

Sorry, I didn't notice the call to `elm_overlayframe.hpp` in `gui_playlist.cpp` so I tried to copy the one you implemented in browser. Already reverted.

**Comment by HookedBehemoth** [comment]
thanks

**Pull request merged**
